spring:
  flyway:
    baselineOnMigrate: true
    cleanDisabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://backup.saraqian.cn:3306/wishlist?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: wishlist
    password: Asdfzxcv88
app:
  appId: "wxa823794835f994b3"
  appSecret: "1e0d9911438978e850061262a1c58889"
info:
  github: https://github.com/abigail830/wish-list-jpa.git
  jitpack: https://jitpack.io/#abigail830/wish-list-jpa
server:
  port: 8083





